title: GSS Nettoyage Genève – Entreprise de nettoyage à Genève
description: Entreprise de nettoyage à Genève spécialisée en nettoyage de bureaux, fin de bail, fin de chantier et conciergerie dans le canton de Genève.

url: "https://gssnettoyage.github.io"
baseurl: "/gss_nettoyage_renovation_geneve_suisse"

theme: minima

lang: fr
timezone: Europe/Zurich

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

seo:
  type: Organization
  canonical: false

organization:
  name: GSS Nettoyage Genève
  url: https://gssnettoyage.ch

social:
  name: GSS Nettoyage Genève
